
TARGET_CPU_ABI := armeabi-v5te
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv5te

TARGET_BOARD_PLATFORM := asus

TARGET_NO_BOOTLOADER := true
TARGET_NO_KERNEL := true
TARGET_NO_RADIOIMAGE := true
TARGET_NO_RECOVERY := true

TARGET_BOOTIMAGE_USE_EXT2 := true
TARGET_USERIMAGES_USE_EXT2 := true
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := true

TARGET_PROVIDES_INIT_RC := true

# Flash Partition size limits for build sanity checking
#
BOARD_BOOTIMAGE_MAX_SIZE := 2621440
BOARD_SYSTEMIMAGE_MAX_SIZE := 70778880
BOARD_USERDATAIMAGE_MAX_SIZE := 78381056

BOARD_FLASH_BLOCK_SIZE := 4096

BOARD_HAVE_BLUETOOTH := false
BOARD_USES_GENERIC_AUDIO := true
USE_CAMERA_STUB := true
